/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./src/components/modals/ActionButton.vue')['default']
    ActionCategory: typeof import('./src/components/modals/ActionCategory.vue')['default']
    ActionDisplay: typeof import('./src/components/modals/ActionDisplay.vue')['default']
    ActionsDisplay: typeof import('./src/components/modals/ActionsDisplay.vue')['default']
    ActionsDisplay2: typeof import('./src/components/modals/ActionsDisplay2.vue')['default']
    ActionsSelection: typeof import('./src/components/modals/ActionsSelection.vue')['default']
    BindingOptionsDrawer: typeof import('./src/components/homePage/BindingOptionsDrawer.vue')['default']
    Button: typeof import('primevue/button')['default']
    ButtonBindingsMain: typeof import('./src/components/homePage/ButtonBindingsMain.vue')['default']
    ButtonBox: typeof import('./src/components/homePage/ButtonBox.vue')['default']
    ButtonsDisplayMain: typeof import('./src/components/ButtonsDisplayMain.vue')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    DefaultAction: typeof import('./src/components/modals/actionNodes/DefaultAction.vue')['default']
    DefaultActionNode: typeof import('./src/components/modals/actionNodes/DefaultActionNode.vue')['default']
    DelayNode: typeof import('./src/components/modals/actionNodes/DelayNode.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeCenterSection: typeof import('./src/components/homePage/HomeCenterSection.vue')['default']
    HomeKnob: typeof import('./src/components/homePage/HomeKnob.vue')['default']
    HomeLeftButtonSection: typeof import('./src/components/homePage/HomeLeftButtonSection.vue')['default']
    HomeRightLogArea: typeof import('./src/components/homePage/HomeRightLogArea.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    KeyPressNode: typeof import('./src/components/modals/actionNodes/KeyPressNode.vue')['default']
    KnobBindingDialog: typeof import('./src/components/modals/KnobBindingDialog.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    MouseClickNode: typeof import('./src/components/modals/actionNodes/MouseClickNode.vue')['default']
    MouseMoveNode: typeof import('./src/components/modals/actionNodes/MouseMoveNode.vue')['default']
    MultiBindingDialog: typeof import('./src/components/modals/MultiBindingDialog.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RoundPageButton: typeof import('./src/components/homePage/RoundPageButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Terminal: typeof import('primevue/terminal')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Timeline: typeof import('primevue/timeline')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
    WrenchIcon: typeof import('./src/components/icons/WrenchIcon.vue')['default']
    WriteActionNode: typeof import('./src/components/modals/actionNodes/WriteActionNode.vue')['default']
  }
}
